### ISSUE TITLE
Plugin no longer works for some reason.

### ISSUE THREAD

**Issue by BrettPlays** [ipsk/Holovid#17]
So i've been running it fine on 1.16.2 Tuinity for a while now and all of a sudden I start up the server today and it loads in fine yet doesn't want to spawn the screen. Any ideas? Am on Java 8.
https://pastebin.com/raw/81NUYTwr

**Comment by Chasewhip8** [comment]
The plugin is updated to 1.16.3.

**Comment by BrettPlays** [comment]
Unfortunately it doesn't seem to want to work: https://pastebin.com/raw/euvjqsed

**Comment by LichtHund** [comment]
Make sure you're building with shadowJar to shade the command framework

**Comment by BrettPlays** [comment]
I got it to compile now but it seems to crash everytime I play a video, no matter the length. Granted this is my screen size:
`display-height: 120
display-width: 180`
Although I have 6GB on a tuinity server which seems really odd... it worked fine on 1.16.2.

**Comment by Chasewhip8** [comment]
Try using either 72x128 or 144x256

**Comment by BrettPlays** [comment]
Same issue, I also get [this ](https://pastebin.com/raw/HN5ME7X3)error when I play the already downloaded video but I would presume that has to do with me not being able to change/setup the server properly. [Here ](https://pastebin.com/raw/1w3CUunh)is the log file btw.

**Comment by Chasewhip8** [comment]
You currently need to delete the data folder inside of the plugin folder. The previously saved videos are saved with the wacky resolutions. We do not support non standard resolutions as of now tru and stick to the ones I mentioned above

**Comment by BrettPlays** [comment]
Okay so i'm having mixed/random results. At first it was crashing but it now seems to be working apart from the obvious resource pack thing. The server has 6 GB though and the plugin always seems to bring it down to 18 TPS which is odd. [Here ](https://timings.aikar.co/?id=e80c1f23675f4e02b217151619155a5d)is a timings report if this will help diagnose any issues. One thing I noticed is that the video slowed down and sped up at random times which would make it off sync with the audio from my custom resource pack, is there any way to fix this?
Thank You though!

**Comment by BrettPlays** [comment]
Updated to 1.16.4. https://pastebin.com/raw/CiKRyGK5
